name: AWS CDK Synth

on:
  push:
    branches:
      - master
jobs:
  aws-cdk-synth:

    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: npm install, build and test
      run: |
        npm install
        npm run build --if-present
        npm test


    - name: CDK Deploy
      uses: scottbrenner/aws-cdk-action@master
      with:
        args: deploy
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
